// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.2

package types

type FindUserRequest struct {
	Name  string   `json:"name"`
	Phone string   `json:"phone"`
	Ids   []string `json:"ids"`
}

type FindUserResponse struct {
	User []UserEntity `json:"user"`
}

type GetUserInfoRequest struct {
	Id string `json:"id"`
}

type GetUserInfoResponse struct {
	User UserEntity `json:"user"`
}

type LoginRequest struct {
	Phone    string `json:"phone"`
	Password string `json:"password"`
}

type LoginResponse struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type RegisterRequest struct {
	Phone    string `json:"phone"`
	Nickname string `json:"nickname"`
	Password string `json:"password"`
	Avatar   string `json:"avatar"`
	Sex      int32  `json:"sex"`
}

type RegisterResponse struct {
	Token  string `json:"token"`
	Expire int64  `json:"expire"`
}

type Request struct {
	Ping string `json:"ping"`
}

type Response struct {
	Pong string `json:"pong"`
}

type UserEntity struct {
	Id       string `json:"id"`
	Avatar   string `json:"avatar"`
	Nickname string `json:"nickname"`
	Phone    string `json:"phone"`
	Status   int32  `json:"status"`
	Sex      int32  `json:"sex"`
}
